//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.19 at 11:58:39 \u043f\u043e\u043f\u043b. CET 
//


package allapis.com.example.webservices;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the allapis.com.example.webservices package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: allapis.com.example.webservices
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ClubInfo }
     * 
     */
    public ClubInfo createClubInfo() {
        return new ClubInfo();
    }

    /**
     * Create an instance of {@link DeleteClubRequest }
     * 
     */
    public DeleteClubRequest createDeleteClubRequest() {
        return new DeleteClubRequest();
    }

    /**
     * Create an instance of {@link GetClubByIdRequest }
     * 
     */
    public GetClubByIdRequest createGetClubByIdRequest() {
        return new GetClubByIdRequest();
    }

    /**
     * Create an instance of {@link GetClubResponse }
     * 
     */
    public GetClubResponse createGetClubResponse() {
        return new GetClubResponse();
    }

    /**
     * Create an instance of {@link AddEmployeeRequest }
     * 
     */
    public AddEmployeeRequest createAddEmployeeRequest() {
        return new AddEmployeeRequest();
    }

    /**
     * Create an instance of {@link DeleteClubResponse }
     * 
     */
    public DeleteClubResponse createDeleteClubResponse() {
        return new DeleteClubResponse();
    }

    /**
     * Create an instance of {@link ServiceStatus }
     * 
     */
    public ServiceStatus createServiceStatus() {
        return new ServiceStatus();
    }

    /**
     * Create an instance of {@link AddClubResponse }
     * 
     */
    public AddClubResponse createAddClubResponse() {
        return new AddClubResponse();
    }

}
