//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.02.19 at 11:58:39 \u043f\u043e\u043f\u043b. CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://webservices.example.com.allapis", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package allapis.com.example.webservices;
