//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.17 at 11:55:32 PM CEST 
//


package com.mcnz.jee.soap;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="clubDto" type="{http://soap.jee.mcnz.com/}clubDto"/&gt;
 *         &lt;element name="statusMessage" type="{http://soap.jee.mcnz.com/}statusMessage"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "clubDto",
    "statusMessage"
})
@XmlRootElement(name = "getClubResponse")
public class GetClubResponse {

    @XmlElement(required = true)
    protected ClubDto clubDto;
    @XmlElement(required = true)
    protected StatusMessage statusMessage;

    /**
     * Gets the value of the clubDto property.
     * 
     * @return
     *     possible object is
     *     {@link ClubDto }
     *     
     */
    public ClubDto getClubDto() {
        return clubDto;
    }

    /**
     * Sets the value of the clubDto property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClubDto }
     *     
     */
    public void setClubDto(ClubDto value) {
        this.clubDto = value;
    }

    /**
     * Gets the value of the statusMessage property.
     * 
     * @return
     *     possible object is
     *     {@link StatusMessage }
     *     
     */
    public StatusMessage getStatusMessage() {
        return statusMessage;
    }

    /**
     * Sets the value of the statusMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatusMessage }
     *     
     */
    public void setStatusMessage(StatusMessage value) {
        this.statusMessage = value;
    }

}
