//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.17 at 11:55:32 PM CEST 
//


package com.mcnz.jee.soap;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mcnz.jee.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mcnz.jee.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetClubRequest }
     * 
     */
    public GetClubRequest createGetClubRequest() {
        return new GetClubRequest();
    }

    /**
     * Create an instance of {@link GetClubResponse }
     * 
     */
    public GetClubResponse createGetClubResponse() {
        return new GetClubResponse();
    }

    /**
     * Create an instance of {@link ClubDto }
     * 
     */
    public ClubDto createClubDto() {
        return new ClubDto();
    }

    /**
     * Create an instance of {@link StatusMessage }
     * 
     */
    public StatusMessage createStatusMessage() {
        return new StatusMessage();
    }

    /**
     * Create an instance of {@link GetAllClubsRequest }
     * 
     */
    public GetAllClubsRequest createGetAllClubsRequest() {
        return new GetAllClubsRequest();
    }

    /**
     * Create an instance of {@link GetAllClubsResponse }
     * 
     */
    public GetAllClubsResponse createGetAllClubsResponse() {
        return new GetAllClubsResponse();
    }

    /**
     * Create an instance of {@link CreateClubRequest }
     * 
     */
    public CreateClubRequest createCreateClubRequest() {
        return new CreateClubRequest();
    }

    /**
     * Create an instance of {@link CreateClubDto }
     * 
     */
    public CreateClubDto createCreateClubDto() {
        return new CreateClubDto();
    }

    /**
     * Create an instance of {@link CreateClubResponse }
     * 
     */
    public CreateClubResponse createCreateClubResponse() {
        return new CreateClubResponse();
    }

    /**
     * Create an instance of {@link UpdateClubRequest }
     * 
     */
    public UpdateClubRequest createUpdateClubRequest() {
        return new UpdateClubRequest();
    }

    /**
     * Create an instance of {@link UpdateClubResponse }
     * 
     */
    public UpdateClubResponse createUpdateClubResponse() {
        return new UpdateClubResponse();
    }

    /**
     * Create an instance of {@link DeleteClubRequest }
     * 
     */
    public DeleteClubRequest createDeleteClubRequest() {
        return new DeleteClubRequest();
    }

    /**
     * Create an instance of {@link DeleteClubResponse }
     * 
     */
    public DeleteClubResponse createDeleteClubResponse() {
        return new DeleteClubResponse();
    }

    /**
     * Create an instance of {@link DeleteMyClubsRequest }
     * 
     */
    public DeleteMyClubsRequest createDeleteMyClubsRequest() {
        return new DeleteMyClubsRequest();
    }

    /**
     * Create an instance of {@link DeleteMyClubsResponse }
     * 
     */
    public DeleteMyClubsResponse createDeleteMyClubsResponse() {
        return new DeleteMyClubsResponse();
    }



}
