//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.06.13 at 02:04:24 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://soap.jee.mcnz.com/", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.mcnz.jee.soap;
